<?php
if (!function_exists('hiring_e')) { function hiring_e($v){ return htmlspecialchars((string)($v ?? ''), ENT_QUOTES, 'UTF-8'); } }
if (!function_exists('hiring_uid')) { function hiring_uid(){ return (int)($_SESSION['user_id'] ?? 0); } }
if (!function_exists('hiring_eid')) { function hiring_eid($conn){ if(!empty($_SESSION['employee_id'])) return (int)$_SESSION['employee_id']; if(!empty($_SESSION['user_id'])){ $uid=(int)$_SESSION['user_id']; $q=mysqli_query($conn,"SELECT employee_id FROM users WHERE id=$uid LIMIT 1"); if($q && ($r=mysqli_fetch_assoc($q)) && !empty($r['employee_id'])){ $_SESSION['employee_id']=(int)$r['employee_id']; return (int)$r['employee_id']; }} return 0; } }
if (!function_exists('hiring_is_super_admin')) { function hiring_is_super_admin($conn){ $uid=hiring_uid(); if($uid<=0) return false; $q=mysqli_query($conn,"SELECT r.id FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=$uid AND (r.id=1 OR r.role_slug='super-admin' OR LOWER(r.role_name)='super admin') LIMIT 1"); return $q && mysqli_num_rows($q)>0; } }
if (!function_exists('hiring_can')) { function hiring_can($conn,$perm){ if(hiring_is_super_admin($conn)) return true; if(!in_array($perm,['can_view','can_create','can_edit','can_delete'],true)) return false; $uid=hiring_uid(); if($uid<=0) return false; $q=mysqli_query($conn,"SELECT MAX(COALESCE(rsa.`$perm`,0)) ok FROM user_roles ur INNER JOIN role_sidebar_access rsa ON rsa.role_id=ur.role_id INNER JOIN sidebar_menus sm ON sm.id=rsa.menu_id WHERE ur.user_id=$uid AND sm.menu_url='hirings.php' AND sm.is_active=1"); return $q && ($r=mysqli_fetch_assoc($q)) && (int)($r['ok']??0)===1; } }
if (!function_exists('hiring_next_code')) { function hiring_next_code($conn,$table,$col,$prefix){ $like=mysqli_real_escape_string($conn,$prefix.date('Ym').'-'); $q=mysqli_query($conn,"SELECT `$col` code FROM `$table` WHERE `$col` LIKE '$like%' ORDER BY id DESC LIMIT 1"); $n=1; if($q && ($r=mysqli_fetch_assoc($q))){ $p=explode('-',(string)$r['code']); $n=max(1,(int)end($p)+1); } return $prefix.date('Ym').'-'.str_pad((string)$n,4,'0',STR_PAD_LEFT); } }
if (!function_exists('hiring_date_or_null')) { function hiring_date_or_null($v){ $v=trim((string)$v); return ($v==='' || $v==='0000-00-00') ? null : $v; } }
if (!function_exists('hiring_log')) { function hiring_log($conn,$entity,$id,$type,$old=null,$new=null,$remarks=''){ $entity=mysqli_real_escape_string($conn,$entity); $id=(int)$id; $type=mysqli_real_escape_string($conn,$type); $oldSql=$old===null?'NULL':"'".mysqli_real_escape_string($conn,(string)$old)."'"; $newSql=$new===null?'NULL':"'".mysqli_real_escape_string($conn,(string)$new)."'"; $rem=mysqli_real_escape_string($conn,$remarks); $eid=hiring_eid($conn); $uid=hiring_uid(); $ip=mysqli_real_escape_string($conn,$_SERVER['REMOTE_ADDR']??''); mysqli_query($conn,"INSERT INTO hiring_actions(entity_type,entity_id,action_type,old_status,new_status,remarks,action_by_employee_id,action_by_user_id,ip_address) VALUES('$entity',$id,'$type',$oldSql,$newSql,'$rem',".($eid?:'NULL').",".($uid?:'NULL').",'$ip')"); $name=mysqli_real_escape_string($conn,$_SESSION['employee_name']??$_SESSION['name']??''); $user=mysqli_real_escape_string($conn,$_SESSION['username']??''); $des=mysqli_real_escape_string($conn,$_SESSION['designation']??''); $dep=mysqli_real_escape_string($conn,$_SESSION['department']??''); $desc=mysqli_real_escape_string($conn,"Hiring $type: $remarks"); $atype=mysqli_real_escape_string($conn,strtoupper($type)); mysqli_query($conn,"INSERT INTO activity_logs(employee_id,employee_name,username,designation,department,activity_type,module,description,reference_id,ip_address) VALUES(".($eid?:'NULL').",'$name','$user','$des','$dep','$atype','Hiring','$desc',$id,'$ip')"); } }


if (!function_exists('hiring_badge_class')) {
    function hiring_badge_class($status) {
        $status = strtolower((string)$status);
        if (in_array($status, ['open','active','selected','approved','joined','converted','onboarded','passed','completed','pass','select','next_round'], true)) return 'green';
        if (in_array($status, ['draft','applied','screening','shortlisted','interview','scheduled','pending_approval','pending','hold'], true)) return 'amber';
        if (in_array($status, ['rejected','failed','cancelled','closed','withdrawn','no_show','fail'], true)) return 'red';
        return 'blue';
    }
}
?>